var _qtlDocs = (function(){
  var B = 'https://www.qtl.lighting/Customer-Content/www/products/Files/SPEC_SHEET/';
  var F = 'https://www.qtl.lighting/Customer-Content/www/products/Files/';
  return [
    // ── BOOM ──
    {name:'BOOM-CROSS-SHAPE (01)',    cat:'BOOM', desc:'Multi-shape BOOM pendant — cross shape.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    {name:'BOOM-FIXED (01)',          cat:'BOOM', desc:'Fixed-mount single BOOM pendant fixture.',url:B+'QTL_BOOM-Fixed_01_Single_.pdf'},
    {name:'BOOM-INLINE (01)',         cat:'BOOM', desc:'Inline BOOM pendant configuration.',url:B+'QTL_BOOM-Inline_01.pdf'},
    {name:'BOOM-L-SHAPE (01)',        cat:'BOOM', desc:'L-shape BOOM pendant fixture.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    {name:'BOOM-POA (01)',            cat:'BOOM', desc:'Point-of-attachment BOOM pendant.',url:B+'QTL_BOOM-SinglePOA_01.pdf'},
    {name:'BOOM-RECTANGLE-SHAPE (01)',cat:'BOOM', desc:'Rectangle-shape BOOM pendant fixture.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    {name:'BOOM-SINGLE (01)',         cat:'BOOM', desc:'Single BOOM pendant fixture.',url:B+'QTL_BOOM-Single_01.pdf'},
    {name:'BOOM-SQUARE-SHAPE (01)',   cat:'BOOM', desc:'Square-shape BOOM pendant fixture.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    {name:'BOOM-T-SHAPE (01)',        cat:'BOOM', desc:'T-shape BOOM pendant fixture.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    {name:'BOOM-U-SHAPE (01)',        cat:'BOOM', desc:'U-shape BOOM pendant fixture.',url:B+'QTL_BOOM-Shapes_01.pdf'},
    // ── ESSENTIALS ARKA ──
    {name:'ARKA-FLAT (01) RGB',             cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — RGB.',url:B+'QTL_ARKA-FLAT__01__RGB.pdf'},
    {name:'ARKA-FLAT (01) RGBW',            cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — RGBW/RGBW-HE.',url:B+'QTL_ARKA-FLAT__01__RGBW.pdf'},
    {name:'ARKA-FLAT (01) Static Color',    cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — static color.',url:B+'QTL_ARKA-FLAT__01__STATIC_COLOR.pdf'},
    {name:'ARKA-FLAT (01) Static White',    cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — static white.',url:B+'QTL_ARKA-FLAT__01__STATIC_WHITE.pdf'},
    {name:'ARKA-FLAT (01) Static White HE', cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — static white high efficacy.',url:B+'QTL_ARKA-FLAT__01__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'ARKA-FLAT (01) Tunable',         cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — tunable white.',url:B+'QTL_ARKA-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ARKA-FLAT (01) Warm Dim',        cat:'Essentials Linear', desc:'ARKA flat profile linear fixture — warm dim.',url:B+'QTL_ARKA-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS EMBD ──
    {name:'EMBD-ENCAPSULATED (03) RGB',             cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — RGB.',url:B+'QTL_EMBD-ENCAPSULATED__03__RGB.pdf'},
    {name:'EMBD-ENCAPSULATED (03) RGBW',            cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — RGBW/RGBW-HE.',url:B+'QTL_EMBD-ENCAPSULATED__03__RGBW.pdf'},
    {name:'EMBD-ENCAPSULATED (03) Static Color',    cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — static color.',url:B+'QTL_EMBD-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'EMBD-ENCAPSULATED (03) Static White',    cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — static white/HE.',url:B+'QTL_EMBD-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'EMBD-ENCAPSULATED (03) Tunable',         cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — tunable.',url:B+'QTL_EMBD-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'EMBD-ENCAPSULATED (03) Warm Dim',        cat:'Essentials Linear', desc:'EMBD encapsulated linear fixture — warm dim.',url:B+'QTL_EMBD-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'EMBD-FLAT (01) RGB',                     cat:'Essentials Linear', desc:'EMBD flat linear fixture — RGB.',url:B+'QTL_EMBD-FLAT__01__RGB.pdf'},
    {name:'EMBD-FLAT (01) RGBW',                    cat:'Essentials Linear', desc:'EMBD flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_EMBD-FLAT__01__RGBW.pdf'},
    {name:'EMBD-FLAT (01) Static Color',            cat:'Essentials Linear', desc:'EMBD flat linear fixture — static color.',url:B+'QTL_EMBD-FLAT__01__STATIC_COLOR.pdf'},
    {name:'EMBD-FLAT (01) Static White',            cat:'Essentials Linear', desc:'EMBD flat linear fixture — static white.',url:B+'QTL_EMBD-FLAT__01__STATIC_WHITE.pdf'},
    {name:'EMBD-FLAT (01) Static White HE',         cat:'Essentials Linear', desc:'EMBD flat linear fixture — static white high efficacy.',url:B+'QTL_EMBD-FLAT__01__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'EMBD-FLAT (01) Tunable',                 cat:'Essentials Linear', desc:'EMBD flat linear fixture — tunable.',url:B+'QTL_EMBD-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'EMBD-FLAT (01) Warm Dim',                cat:'Essentials Linear', desc:'EMBD flat linear fixture — warm dim.',url:B+'QTL_EMBD-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'EMBD-OPTICS (02) RGB',                   cat:'Essentials Linear', desc:'EMBD optics linear fixture — RGB.',url:B+'QTL_EMBD-OPTICS__02__RGB.pdf'},
    {name:'EMBD-OPTICS (02) RGBW',                  cat:'Essentials Linear', desc:'EMBD optics linear fixture — RGBW.',url:B+'QTL_EMBD-OPTICS__02__RGBW.pdf'},
    {name:'EMBD-OPTICS (02) Static Color',          cat:'Essentials Linear', desc:'EMBD optics linear fixture — static color.',url:B+'QTL_EMBD-OPTICS__02__STATIC_COLOR.pdf'},
    {name:'EMBD-OPTICS (02) Static White',          cat:'Essentials Linear', desc:'EMBD optics linear fixture — static white/HE.',url:B+'QTL_EMBD-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'EMBD-OPTICS (02) Static White HE',       cat:'Essentials Linear', desc:'EMBD optics linear fixture — static white high efficacy.',url:B+'QTL_EMBD-OPTICS__02__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'EMBD-OPTICS (02) Tunable',               cat:'Essentials Linear', desc:'EMBD optics linear fixture — tunable.',url:B+'QTL_EMBD-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'EMBD-OPTICS (02) Warm Dim',              cat:'Essentials Linear', desc:'EMBD optics linear fixture — warm dim.',url:B+'QTL_EMBD-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS FLUR ──
    {name:'FLUR-ENCAPSULATED (03) RGB',          cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — RGB.',url:B+'QTL_FLUR-ENCAPSULATED__03__RGB.pdf'},
    {name:'FLUR-ENCAPSULATED (03) RGBW',         cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — RGBW.',url:B+'QTL_FLUR-ENCAPSULATED__03__RGBW.pdf'},
    {name:'FLUR-ENCAPSULATED (03) Static Color', cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — static color.',url:B+'QTL_FLUR-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'FLUR-ENCAPSULATED (03) Static White', cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — static white.',url:B+'QTL_FLUR-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'FLUR-ENCAPSULATED (03) Tunable',      cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — tunable.',url:B+'QTL_FLUR-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'FLUR-ENCAPSULATED (03) Warm Dim',     cat:'Essentials Linear', desc:'FLUR encapsulated linear fixture — warm dim.',url:B+'QTL_FLUR-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'FLUR-FLAT (01) RGB',                  cat:'Essentials Linear', desc:'FLUR flat linear fixture — RGB.',url:B+'QTL_FLUR-FLAT__01__RGB.pdf'},
    {name:'FLUR-FLAT (01) RGBW',                 cat:'Essentials Linear', desc:'FLUR flat linear fixture — RGBW high efficacy.',url:B+'QTL_FLUR-FLAT__01__RGBW.pdf'},
    {name:'FLUR-FLAT (01) Static Color',         cat:'Essentials Linear', desc:'FLUR flat linear fixture — static color.',url:B+'QTL_FLUR-FLAT__01__STATIC_COLOR.pdf'},
    {name:'FLUR-FLAT (01) Static White',         cat:'Essentials Linear', desc:'FLUR flat linear fixture — static white/HE.',url:B+'QTL_FLUR-FLAT__01__STATIC_WHITE.pdf'},
    {name:'FLUR-FLAT (01) Tunable',              cat:'Essentials Linear', desc:'FLUR flat linear fixture — tunable.',url:B+'QTL_FLUR-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'FLUR-FLAT (01) Warm Dim',             cat:'Essentials Linear', desc:'FLUR flat linear fixture — warm dim.',url:B+'QTL_FLUR-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS LALO ──
    {name:'LALO-ENCAPSULATED (03) RGB',              cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — RGB.',url:B+'QTL_LALO-ENCAPSULATED__03__RGB.pdf'},
    {name:'LALO-ENCAPSULATED (03) RGBW',             cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LALO-ENCAPSULATED__03__RGBW.pdf'},
    {name:'LALO-ENCAPSULATED (03) Static Color',     cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — static color.',url:B+'QTL_LALO-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'LALO-ENCAPSULATED (03) Static White',     cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — static white/HE.',url:B+'QTL_LALO-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'LALO-ENCAPSULATED (03) Tunable',          cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — tunable.',url:B+'QTL_LALO-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'LALO-ENCAPSULATED (03) Warm Dim',         cat:'Essentials Linear', desc:'LALO encapsulated linear fixture — warm dim.',url:B+'QTL_LALO-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'LALO-FLAT (01) RGB',                      cat:'Essentials Linear', desc:'LALO flat linear fixture — RGB.',url:B+'QTL_LALO-FLAT__01__RGB.pdf'},
    {name:'LALO-FLAT (01) RGBW',                     cat:'Essentials Linear', desc:'LALO flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LALO-FLAT__01__RGBW.pdf'},
    {name:'LALO-FLAT (01) Static Color',             cat:'Essentials Linear', desc:'LALO flat linear fixture — static color.',url:B+'QTL_LALO-FLAT__01__STATIC_COLOR.pdf'},
    {name:'LALO-FLAT (01) Static White',             cat:'Essentials Linear', desc:'LALO flat linear fixture — static white.',url:B+'QTL_LALO-FLAT__01__STATIC_WHITE.pdf'},
    {name:'LALO-FLAT (01) Static White HE',          cat:'Essentials Linear', desc:'LALO flat linear fixture — static white high efficacy.',url:B+'QTL_LALO-FLAT__01__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'LALO-FLAT (01) Tunable',                  cat:'Essentials Linear', desc:'LALO flat linear fixture — tunable.',url:B+'QTL_LALO-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'LALO-FLAT (01) Warm Dim',                 cat:'Essentials Linear', desc:'LALO flat linear fixture — warm dim.',url:B+'QTL_LALO-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'LALO-FLAT-DIMMER (01) Static Color',      cat:'Essentials Linear', desc:'LALO flat linear fixture with integrated dimmer — static color.',url:B+'QTL_LALO-FLAT-DIMMER__01__STATIC_COLOR.pdf'},
    {name:'LALO-FLAT-DIMMER (01) Static White',      cat:'Essentials Linear', desc:'LALO flat linear fixture with integrated dimmer — static white/HE.',url:B+'QTL_LALO-FLAT-DIMMER__01__STATIC_WHITE.pdf'},
    {name:'LALO-FLAT-OCCUPANCY (01) Static Color',   cat:'Essentials Linear', desc:'LALO flat linear fixture with occupancy sensor — static color.',url:B+'QTL_LALO-FLAT-OCCUPANCY__01__STATIC_COLOR.pdf'},
    {name:'LALO-FLAT-OCCUPANCY (01) Static White',   cat:'Essentials Linear', desc:'LALO flat linear fixture with occupancy sensor — static white/HE.',url:B+'QTL_LALO-FLAT-OCCUPANCY__01__STATIC_WHITE.pdf'},
    {name:'LALO-OPTICS (02) RGB',                    cat:'Essentials Linear', desc:'LALO optics linear fixture — RGB.',url:B+'QTL_LALO-OPTICS__02__RGB.pdf'},
    {name:'LALO-OPTICS (02) RGBW',                   cat:'Essentials Linear', desc:'LALO optics linear fixture — RGBW.',url:B+'QTL_LALO-OPTICS__02__RGBW.pdf'},
    {name:'LALO-OPTICS (02) Static Color',           cat:'Essentials Linear', desc:'LALO optics linear fixture — static color.',url:B+'QTL_LALO-OPTICS__02__STATIC_COLOR.pdf'},
    {name:'LALO-OPTICS (02) Static White',           cat:'Essentials Linear', desc:'LALO optics linear fixture — static white/HE.',url:B+'QTL_LALO-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'LALO-OPTICS (02) Tunable',               cat:'Essentials Linear', desc:'LALO optics linear fixture — tunable.',url:B+'QTL_LALO-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'LALO-OPTICS (02) Warm Dim',              cat:'Essentials Linear', desc:'LALO optics linear fixture — warm dim.',url:B+'QTL_LALO-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS LATO ──
    {name:'LATO-ENCAPSULATED (03) RGB',          cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — RGB.',url:B+'QTL_LATO-ENCAPSULATED__03__RGB.pdf'},
    {name:'LATO-ENCAPSULATED (03) RGBW',         cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — RGBW.',url:B+'QTL_LATO-ENCAPSULATED__03__RGBW.pdf'},
    {name:'LATO-ENCAPSULATED (03) Static Color', cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — static color.',url:B+'QTL_LATO-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'LATO-ENCAPSULATED (03) Static White', cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — static white.',url:B+'QTL_LATO-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'LATO-ENCAPSULATED (03) Tunable',      cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — tunable.',url:B+'QTL_LATO-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'LATO-ENCAPSULATED (03) Warm Dim',     cat:'Essentials Linear', desc:'LATO encapsulated linear fixture — warm dim.',url:B+'QTL_LATO-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'LATO-FLAT (01) RGB',                  cat:'Essentials Linear', desc:'LATO flat linear fixture — RGB.',url:B+'QTL_LATO-FLAT__01__RGB.pdf'},
    {name:'LATO-FLAT (01) RGBW',                 cat:'Essentials Linear', desc:'LATO flat linear fixture — RGBW high efficacy.',url:B+'QTL_LATO-FLAT__01__RGBW.pdf'},
    {name:'LATO-FLAT (01) Static Color',         cat:'Essentials Linear', desc:'LATO flat linear fixture — static color.',url:B+'QTL_LATO-FLAT__01__STATIC_COLOR.pdf'},
    {name:'LATO-FLAT (01) Static White',         cat:'Essentials Linear', desc:'LATO flat linear fixture — static white.',url:B+'QTL_LATO-FLAT__01__STATIC_WHITE.pdf'},
    {name:'LATO-FLAT (01) Tunable',              cat:'Essentials Linear', desc:'LATO flat linear fixture — tunable.',url:B+'QTL_LATO-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'LATO-FLAT (01) Warm Dim',             cat:'Essentials Linear', desc:'LATO flat linear fixture — warm dim.',url:B+'QTL_LATO-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS TALO ──
    {name:'TALO-ENCAPSULATED (03) RGB',          cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — RGB.',url:B+'QTL_TALO-ENCAPSULATED__03__RGB.pdf'},
    {name:'TALO-ENCAPSULATED (03) RGBW',         cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — RGBW/RGBW-HE.',url:B+'QTL_TALO-ENCAPSULATED__03__RGBW.pdf'},
    {name:'TALO-ENCAPSULATED (03) Static Color', cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — static color.',url:B+'QTL_TALO-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'TALO-ENCAPSULATED (03) Static White', cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — static white/HE.',url:B+'QTL_TALO-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'TALO-ENCAPSULATED (03) Tunable',      cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — tunable.',url:B+'QTL_TALO-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TALO-ENCAPSULATED (03) Warm Dim',     cat:'Essentials Linear', desc:'TALO encapsulated linear fixture — warm dim.',url:B+'QTL_TALO-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'TALO-FLAT (01) RGB',                  cat:'Essentials Linear', desc:'TALO flat linear fixture — RGB.',url:B+'QTL_TALO-FLAT__01__RGB.pdf'},
    {name:'TALO-FLAT (01) RGBW',                 cat:'Essentials Linear', desc:'TALO flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_TALO-FLAT__01__RGBW.pdf'},
    {name:'TALO-FLAT (01) Static Color',         cat:'Essentials Linear', desc:'TALO flat linear fixture — static color.',url:B+'QTL_TALO-FLAT__01__STATIC_COLOR.pdf'},
    {name:'TALO-FLAT (01) Static White',         cat:'Essentials Linear', desc:'TALO flat linear fixture — static white.',url:B+'QTL_TALO-FLAT__01__STATIC_WHITE.pdf'},
    {name:'TALO-FLAT (01) Static White HE',      cat:'Essentials Linear', desc:'TALO flat linear fixture — static white high efficacy.',url:B+'QTL_TALO-FLAT__01__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'TALO-FLAT (01) Tunable',              cat:'Essentials Linear', desc:'TALO flat linear fixture — tunable.',url:B+'QTL_TALO-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TALO-FLAT (01) Warm Dim',             cat:'Essentials Linear', desc:'TALO flat linear fixture — warm dim.',url:B+'QTL_TALO-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS TELA ──
    {name:'TELA-FLAT (01) RGB',          cat:'Essentials Linear', desc:'TELA flat linear fixture — RGB.',url:B+'QTL_TELA-FLAT__01__RGB.pdf'},
    {name:'TELA-FLAT (01) RGBW',         cat:'Essentials Linear', desc:'TELA flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_TELA-FLAT__01__RGBW.pdf'},
    {name:'TELA-FLAT (01) Static Color', cat:'Essentials Linear', desc:'TELA flat linear fixture — static color.',url:B+'QTL_TELA-FLAT__01__STATIC_COLOR.pdf'},
    {name:'TELA-FLAT (01) Static White', cat:'Essentials Linear', desc:'TELA flat linear fixture — static white/HE.',url:B+'QTL_TELA-FLAT__01__STATIC_WHITE.pdf'},
    {name:'TELA-FLAT (01) Tunable',      cat:'Essentials Linear', desc:'TELA flat linear fixture — tunable.',url:B+'QTL_TELA-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TELA-FLAT (01) Warm Dim',     cat:'Essentials Linear', desc:'TELA flat linear fixture — warm dim.',url:B+'QTL_TELA-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS THIN ──
    {name:'THIN-FLAT (01) RGB',                cat:'Essentials Linear', desc:'THIN flat slim linear fixture — RGB.',url:B+'QTL_THIN-FLAT__01__RGB.pdf'},
    {name:'THIN-FLAT (01) RGBW',               cat:'Essentials Linear', desc:'THIN flat slim linear fixture — RGBW/RGBW-HE.',url:B+'QTL_THIN-FLAT__01__RGBW.pdf'},
    {name:'THIN-FLAT (01) Static White SCOB',  cat:'Essentials Linear', desc:'THIN flat slim linear fixture — static white SCOB.',url:B+'QTL_THIN-FLAT__01__STATIC_WHITE_SCOB.pdf'},
    {name:'THIN-FLAT (01) Static Color',       cat:'Essentials Linear', desc:'THIN flat slim linear fixture — static color.',url:B+'QTL_THIN-FLAT__01__STATIC_COLOR.pdf'},
    {name:'THIN-FLAT (01) Static White',       cat:'Essentials Linear', desc:'THIN flat slim linear fixture — static white.',url:B+'QTL_THIN-FLAT__01__STATIC_WHITE.pdf'},
    {name:'THIN-FLAT (01) Static White HE',    cat:'Essentials Linear', desc:'THIN flat slim linear fixture — static white high efficacy.',url:B+'QTL_THIN-FLAT__01__STATIC_WHITE_HIGH_EFFICACY.pdf'},
    {name:'THIN-FLAT (01) Tunable',            cat:'Essentials Linear', desc:'THIN flat slim linear fixture — tunable.',url:B+'QTL_THIN-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'THIN-FLAT (01) Warm Dim',           cat:'Essentials Linear', desc:'THIN flat slim linear fixture — warm dim.',url:B+'QTL_THIN-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS TORQ ──
    {name:'TORQ-ENCAPSULATED (03) RGB',          cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — RGB.',url:B+'QTL_TORQ-ENCAPSULATED__03__RGB.pdf'},
    {name:'TORQ-ENCAPSULATED (03) RGBW',         cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — RGBW.',url:B+'QTL_TORQ-ENCAPSULATED__03__RGBW.pdf'},
    {name:'TORQ-ENCAPSULATED (03) Static Color', cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — static color.',url:B+'QTL_TORQ-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'TORQ-ENCAPSULATED (03) Static White', cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — static white/HE.',url:B+'QTL_TORQ-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'TORQ-ENCAPSULATED (03) Tunable',      cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — tunable.',url:B+'QTL_TORQ-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TORQ-ENCAPSULATED (03) Warm Dim',     cat:'Essentials Linear', desc:'TORQ encapsulated linear fixture — warm dim.',url:B+'QTL_TORQ-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'TORQ-FLAT (01) RGB',                  cat:'Essentials Linear', desc:'TORQ flat linear fixture — RGB.',url:B+'QTL_TORQ-FLAT__01__RGB.pdf'},
    {name:'TORQ-FLAT (01) RGBW',                 cat:'Essentials Linear', desc:'TORQ flat linear fixture — RGBW high efficacy.',url:B+'QTL_TORQ-FLAT__01__RGBW.pdf'},
    {name:'TORQ-FLAT (01) Static Color',         cat:'Essentials Linear', desc:'TORQ flat linear fixture — static color.',url:B+'QTL_TORQ-FLAT__01__STATIC_COLOR.pdf'},
    {name:'TORQ-FLAT (01) Static White',         cat:'Essentials Linear', desc:'TORQ flat linear fixture — static white/HE.',url:B+'QTL_TORQ-FLAT__01__STATIC_WHITE.pdf'},
    {name:'TORQ-FLAT (01) Tunable',              cat:'Essentials Linear', desc:'TORQ flat linear fixture — tunable.',url:B+'QTL_TORQ-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TORQ-FLAT (01) Warm Dim',             cat:'Essentials Linear', desc:'TORQ flat linear fixture — warm dim.',url:B+'QTL_TORQ-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'TORQ-OPTICS (02) RGB',                cat:'Essentials Linear', desc:'TORQ optics linear fixture — RGB.',url:B+'QTL_TORQ-OPTICS__02__RGB.pdf'},
    {name:'TORQ-OPTICS (02) Static Color',       cat:'Essentials Linear', desc:'TORQ optics linear fixture — static color.',url:B+'QTL_TORQ-OPTICS__02__STATIC_COLOR.pdf'},
    {name:'TORQ-OPTICS (02) Static White',       cat:'Essentials Linear', desc:'TORQ optics linear fixture — static white/HE.',url:B+'QTL_TORQ-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'TORQ-OPTICS (02) Tunable',            cat:'Essentials Linear', desc:'TORQ optics linear fixture — tunable.',url:B+'QTL_TORQ-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TORQ-OPTICS (02) Warm Dim',           cat:'Essentials Linear', desc:'TORQ optics linear fixture — warm dim.',url:B+'QTL_TORQ-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS TRE3 ──
    {name:'TRE3-FLAT (01) RGB',          cat:'Essentials Linear', desc:'TRE3 flat linear fixture — RGB.',url:B+'QTL_TRE3-FLAT__01__RGB.pdf'},
    {name:'TRE3-FLAT (01) RGBW',         cat:'Essentials Linear', desc:'TRE3 flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_TRE3-FLAT__01__RGBW.pdf'},
    {name:'TRE3-FLAT (01) Static Color', cat:'Essentials Linear', desc:'TRE3 flat linear fixture — static color.',url:B+'QTL_TRE3-FLAT__01__STATIC_COLOR.pdf'},
    {name:'TRE3-FLAT (01) Static White', cat:'Essentials Linear', desc:'TRE3 flat linear fixture — static white/HE.',url:B+'QTL_TRE3-FLAT__01__STATIC_WHITE.pdf'},
    {name:'TRE3-FLAT (01) Tunable',      cat:'Essentials Linear', desc:'TRE3 flat linear fixture — tunable.',url:B+'QTL_TRE3-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TRE3-FLAT (01) Warm Dim',     cat:'Essentials Linear', desc:'TRE3 flat linear fixture — warm dim.',url:B+'QTL_TRE3-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS VEVE ──
    {name:'VEVE-ENCAPSULATED (03) RGB',          cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — RGB.',url:B+'QTL_VEVE-ENCAPSULATED__03__RGB.pdf'},
    {name:'VEVE-ENCAPSULATED (03) RGBW',         cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — RGBW/RGBW-HE.',url:B+'QTL_VEVE-ENCAPSULATED__03__RGBW.pdf'},
    {name:'VEVE-ENCAPSULATED (03) Static Color', cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — static color.',url:B+'QTL_VEVE-ENCAPSULATED__03__STATIC_COLOR.pdf'},
    {name:'VEVE-ENCAPSULATED (03) Static White', cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — static white/HE.',url:B+'QTL_VEVE-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'VEVE-ENCAPSULATED (03) Tunable',      cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — tunable.',url:B+'QTL_VEVE-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VEVE-ENCAPSULATED (03) Warm Dim',     cat:'Essentials Linear', desc:'VEVE encapsulated linear fixture — warm dim.',url:B+'QTL_VEVE-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VEVE-FLAT (01) RGB',                  cat:'Essentials Linear', desc:'VEVE flat linear fixture — RGB.',url:B+'QTL_VEVE-FLAT__01__RGB.pdf'},
    {name:'VEVE-FLAT (01) RGBW',                 cat:'Essentials Linear', desc:'VEVE flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_VEVE-FLAT__01__RGBW.pdf'},
    {name:'VEVE-FLAT (01) Static Color',         cat:'Essentials Linear', desc:'VEVE flat linear fixture — static color.',url:B+'QTL_VEVE-FLAT__01__STATIC_COLOR.pdf'},
    {name:'VEVE-FLAT (01) Static White',         cat:'Essentials Linear', desc:'VEVE flat linear fixture — static white/HE.',url:B+'QTL_VEVE-FLAT__01__STATIC_WHITE.pdf'},
    {name:'VEVE-FLAT (01) Tunable',              cat:'Essentials Linear', desc:'VEVE flat linear fixture — tunable.',url:B+'QTL_VEVE-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VEVE-FLAT (01) Warm Dim',             cat:'Essentials Linear', desc:'VEVE flat linear fixture — warm dim.',url:B+'QTL_VEVE-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VEVE-OPTICS (02) RGB',                cat:'Essentials Linear', desc:'VEVE optics linear fixture — RGB.',url:B+'QTL_VEVE-OPTICS__02__RGB.pdf'},
    {name:'VEVE-OPTICS (02) RGBW',               cat:'Essentials Linear', desc:'VEVE optics linear fixture — RGBW.',url:B+'QTL_VEVE-OPTICS__02__RGBW.pdf'},
    {name:'VEVE-OPTICS (02) Static Color',       cat:'Essentials Linear', desc:'VEVE optics linear fixture — static color.',url:B+'QTL_VEVE-OPTICS__02__STATIC_COLOR.pdf'},
    {name:'VEVE-OPTICS (02) Static White',       cat:'Essentials Linear', desc:'VEVE optics linear fixture — static white/HE.',url:B+'QTL_VEVE-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'VEVE-OPTICS (02) Tunable',            cat:'Essentials Linear', desc:'VEVE optics linear fixture — tunable.',url:B+'QTL_VEVE-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VEVE-OPTICS (02) Warm Dim',           cat:'Essentials Linear', desc:'VEVE optics linear fixture — warm dim.',url:B+'QTL_VEVE-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── ESSENTIALS WIDE ──
    {name:'WIDE-FLAT (01) RGB',          cat:'Essentials Linear', desc:'WIDE flat linear fixture — RGB.',url:B+'QTL_WIDE-FLAT__01__RGB.pdf'},
    {name:'WIDE-FLAT (01) RGBW',         cat:'Essentials Linear', desc:'WIDE flat linear fixture — RGBW/RGBW-HE.',url:B+'QTL_WIDE-FLAT__01__RGBW.pdf'},
    {name:'WIDE-FLAT (01) Static Color', cat:'Essentials Linear', desc:'WIDE flat linear fixture — static color.',url:B+'QTL_WIDE-FLAT__01__STATIC_COLOR.pdf'},
    {name:'WIDE-FLAT (01) Static White', cat:'Essentials Linear', desc:'WIDE flat linear fixture — static white/HE.',url:B+'QTL_WIDE-FLAT__01__STATIC_WHITE.pdf'},
    {name:'WIDE-FLAT (01) Tunable',      cat:'Essentials Linear', desc:'WIDE flat linear fixture — tunable.',url:B+'QTL_WIDE-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'WIDE-FLAT (01) Warm Dim',     cat:'Essentials Linear', desc:'WIDE flat linear fixture — warm dim.',url:B+'QTL_WIDE-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── MICRO 5 ALTA ──
    {name:'ALTA-DROP (04) RGB',                   cat:'Micro 5', desc:'Micro 5 ALTA drop aperture fixture — RGB.',url:B+'QTL_ALTA-DROP__04__RGB.pdf'},
    {name:'ALTA-DROP (04) Static White',          cat:'Micro 5', desc:'Micro 5 ALTA drop aperture fixture — static white.',url:B+'QTL_ALTA-DROP__04__STATIC_WHITE.pdf'},
    {name:'ALTA-DROP (04) Tunable',               cat:'Micro 5', desc:'Micro 5 ALTA drop aperture fixture — tunable.',url:B+'QTL_ALTA-DROP__04___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ALTA-DROP (04) Warm Dim',              cat:'Micro 5', desc:'Micro 5 ALTA drop aperture fixture — warm dim.',url:B+'QTL_ALTA-DROP__04__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'ALTA-ENCAPSULATED (03) RGB',           cat:'Micro 5', desc:'Micro 5 ALTA encapsulated fixture — RGB.',url:B+'QTL_ALTA-ENCAPSULATED__03__RGB.pdf'},
    {name:'ALTA-ENCAPSULATED (03) Static White',  cat:'Micro 5', desc:'Micro 5 ALTA encapsulated fixture — static white.',url:B+'QTL_ALTA-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'ALTA-ENCAPSULATED (03) Tunable',       cat:'Micro 5', desc:'Micro 5 ALTA encapsulated fixture — tunable.',url:B+'QTL_ALTA-ENCAPSULATED__03___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ALTA-ENCAPSULATED (03) Warm Dim',      cat:'Micro 5', desc:'Micro 5 ALTA encapsulated fixture — warm dim.',url:B+'QTL_ALTA-ENCAPSULATED__03___FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'ALTA-FLAT (01) RGB',                   cat:'Micro 5', desc:'Micro 5 ALTA flat aperture fixture — RGB.',url:B+'QTL_ALTA-FLAT__01__RGB.pdf'},
    {name:'ALTA-FLAT (01) Static White',          cat:'Micro 5', desc:'Micro 5 ALTA flat aperture fixture — static white.',url:B+'QTL_ALTA-FLAT__01__STATIC_WHITE.pdf'},
    {name:'ALTA-FLAT (01) Tunable',               cat:'Micro 5', desc:'Micro 5 ALTA flat aperture fixture — tunable.',url:B+'QTL_ALTA-FLAT__01___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ALTA-FLAT (01) Warm Dim',              cat:'Micro 5', desc:'Micro 5 ALTA flat aperture fixture — warm dim.',url:B+'QTL_ALTA-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'ALTA-OPTICS (02) Static White',        cat:'Micro 5', desc:'Micro 5 ALTA optics fixture — static white.',url:B+'QTL_ALTA-OPTICS__02__STATIC_WHITE.pdf'},
    // ── MICRO 5 ATOM ──
    {name:'ATOM-ENCAPSULATED (03) RGB',           cat:'Micro 5', desc:'Micro 5 ATOM encapsulated fixture — RGB.',url:B+'QTL_ATOM-ENCAPSULATED__03__RGB.pdf'},
    {name:'ATOM-ENCAPSULATED (03) Static White',  cat:'Micro 5', desc:'Micro 5 ATOM encapsulated fixture — static white.',url:B+'QTL_ATOM-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'ATOM-ENCAPSULATED (03) Tunable',       cat:'Micro 5', desc:'Micro 5 ATOM encapsulated fixture — tunable.',url:B+'QTL_ATOM-ENCAPSULATED__03___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ATOM-ENCAPSULATED (03) Warm Dim',      cat:'Micro 5', desc:'Micro 5 ATOM encapsulated fixture — warm dim.',url:B+'QTL_ATOM-ENCAPSULATED__03___FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'ATOM-FLAT (01) RGB',                   cat:'Micro 5', desc:'Micro 5 ATOM flat aperture fixture — RGB.',url:B+'QTL_ATOM-FLAT__01__RGB.pdf'},
    {name:'ATOM-FLAT (01) Static White',          cat:'Micro 5', desc:'Micro 5 ATOM flat aperture fixture — static white.',url:B+'QTL_ATOM-FLAT__01__STATIC_WHITE.pdf'},
    {name:'ATOM-FLAT (01) Tunable',               cat:'Micro 5', desc:'Micro 5 ATOM flat aperture fixture — tunable.',url:B+'QTL_ATOM-FLAT__01___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ATOM-FLAT (01) Warm Dim',              cat:'Micro 5', desc:'Micro 5 ATOM flat aperture fixture — warm dim.',url:B+'QTL_ATOM-FLAT__01___FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'ATOM-OPTICS (02) RGB',                 cat:'Micro 5', desc:'Micro 5 ATOM optics fixture — RGB.',url:B+'QTL_ATOM-OPTICS__02__RGB.pdf'},
    {name:'ATOM-OPTICS (02) Static White',        cat:'Micro 5', desc:'Micro 5 ATOM optics fixture — static white.',url:B+'QTL_ATOM-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'ATOM-OPTICS (02) Tunable',             cat:'Micro 5', desc:'Micro 5 ATOM optics fixture — tunable.',url:B+'QTL_ATOM-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'ATOM-OPTICS (02) Warm Dim',            cat:'Micro 5', desc:'Micro 5 ATOM optics fixture — warm dim.',url:B+'QTL_ATOM-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── MICRO 5 KICKER ──
    {name:'KICKER-ENCAPSULATED (03) RGB',          cat:'Micro 5', desc:'Micro 5 KICKER encapsulated fixture — RGB.',url:B+'QTL_KICKER-ENCAPSULATED__03__RGB.pdf'},
    {name:'KICKER-ENCAPSULATED (03) Static White', cat:'Micro 5', desc:'Micro 5 KICKER encapsulated fixture — static white.',url:B+'QTL_KICKER-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'KICKER-ENCAPSULATED (03) Tunable',      cat:'Micro 5', desc:'Micro 5 KICKER encapsulated fixture — tunable.',url:B+'QTL_KICKER-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'KICKER-ENCAPSULATED (03) Warm Dim',     cat:'Micro 5', desc:'Micro 5 KICKER encapsulated fixture — warm dim.',url:B+'QTL_KICKER-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'KICKER-FLAT (01) RGB',                  cat:'Micro 5', desc:'Micro 5 KICKER flat aperture fixture — RGB.',url:B+'QTL_KICKER-FLAT__01__RGB.pdf'},
    {name:'KICKER-FLAT (01) Static White',         cat:'Micro 5', desc:'Micro 5 KICKER flat aperture fixture — static white.',url:B+'QTL_KICKER-FLAT__01__STATIC_WHITE.pdf'},
    {name:'KICKER-FLAT (01) Tunable',              cat:'Micro 5', desc:'Micro 5 KICKER flat aperture fixture — tunable.',url:B+'QTL_KICKER-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'KICKER-FLAT (01) Warm Dim',             cat:'Micro 5', desc:'Micro 5 KICKER flat aperture fixture — warm dim.',url:B+'QTL_KICKER-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── MICRO 5 POP ──
    {name:'POP FLANGE-ENCAPSULATED (03) RGB',          cat:'Micro 5', desc:'Micro 5 POP flange encapsulated fixture — RGB.',url:B+'QTL_POP_FLANGE-ENCAPSULATED__03__RGB.pdf'},
    {name:'POP FLANGE-ENCAPSULATED (03) Static White', cat:'Micro 5', desc:'Micro 5 POP flange encapsulated fixture — static white.',url:B+'QTL_POP_FLANGE-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'POP FLANGE-ENCAPSULATED (03) Tunable',      cat:'Micro 5', desc:'Micro 5 POP flange encapsulated fixture — tunable.',url:B+'QTL_POP_FLANGE-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP FLANGE-ENCAPSULATED (03) Warm Dim',     cat:'Micro 5', desc:'Micro 5 POP flange encapsulated fixture — warm dim.',url:B+'QTL_POP_FLANGE-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'POP FLANGE-FLAT (01) RGB',                  cat:'Micro 5', desc:'Micro 5 POP flange flat fixture — RGB.',url:B+'QTL_POP_FLANGE-FLAT__01__RGB.pdf'},
    {name:'POP FLANGE-FLAT (01) Static White',         cat:'Micro 5', desc:'Micro 5 POP flange flat fixture — static white.',url:B+'QTL_POP_FLANGE-FLAT__01__STATIC_WHITE.pdf'},
    {name:'POP FLANGE-FLAT (01) Tunable',              cat:'Micro 5', desc:'Micro 5 POP flange flat fixture — tunable.',url:B+'QTL_POP_FLANGE-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP FLANGE-FLAT (01) Warm Dim',             cat:'Micro 5', desc:'Micro 5 POP flange flat fixture — warm dim.',url:B+'QTL_POP_FLANGE-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'POP MUD-IN-ENCAPSULATED (03) RGB',          cat:'Micro 5', desc:'Micro 5 POP mud-in encapsulated fixture — RGB.',url:B+'QTL_POP_MUD-IN-ENCAPSULATED__03__RGB.pdf'},
    {name:'POP MUD-IN-ENCAPSULATED (03) Static White', cat:'Micro 5', desc:'Micro 5 POP mud-in encapsulated fixture — static white.',url:B+'QTL_POP_MUD-IN-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'POP MUD-IN-ENCAPSULATED (03) Tunable',      cat:'Micro 5', desc:'Micro 5 POP mud-in encapsulated fixture — tunable.',url:B+'QTL_POP_MUD-IN-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP MUD-IN-ENCAPSULATED (03) Warm Dim',     cat:'Micro 5', desc:'Micro 5 POP mud-in encapsulated fixture — warm dim.',url:B+'QTL_POP_MUD-IN-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'POP MUD-IN-FLAT (01) RGB',                  cat:'Micro 5', desc:'Micro 5 POP mud-in flat fixture — RGB.',url:B+'QTL_POP_MUD-IN-FLAT__01__RGB.pdf'},
    {name:'POP MUD-IN-FLAT (01) Static White',         cat:'Micro 5', desc:'Micro 5 POP mud-in flat fixture — static white.',url:B+'QTL_POP_MUD-IN-FLAT__01__STATIC_WHITE.pdf'},
    {name:'POP MUD-IN-FLAT (01) Tunable',              cat:'Micro 5', desc:'Micro 5 POP mud-in flat fixture — tunable.',url:B+'QTL_POP_MUD-IN-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP MUD-IN-FLAT (01) Warm Dim',             cat:'Micro 5', desc:'Micro 5 POP mud-in flat fixture — warm dim.',url:B+'QTL_POP_MUD-IN-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'POP-ENCAPSULATED (03) RGB',                 cat:'Micro 5', desc:'Micro 5 POP encapsulated fixture — RGB.',url:B+'QTL_POP-ENCAPSULATED__03__RGB.pdf'},
    {name:'POP-ENCAPSULATED (03) Static White',        cat:'Micro 5', desc:'Micro 5 POP encapsulated fixture — static white.',url:B+'QTL_POP-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'POP-ENCAPSULATED (03) Tunable',             cat:'Micro 5', desc:'Micro 5 POP encapsulated fixture — tunable.',url:B+'QTL_POP-ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP-ENCAPSULATED (03) Warm Dim',            cat:'Micro 5', desc:'Micro 5 POP encapsulated fixture — warm dim.',url:B+'QTL_POP-ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'POP-FLAT (01) RGB',                         cat:'Micro 5', desc:'Micro 5 POP flat fixture — RGB.',url:B+'QTL_POP-FLAT__01__RGB.pdf'},
    {name:'POP-FLAT (01) Static White',                cat:'Micro 5', desc:'Micro 5 POP flat fixture — static white.',url:B+'QTL_POP-FLAT__01__STATIC_WHITE.pdf'},
    {name:'POP-FLAT (01) Tunable',                     cat:'Micro 5', desc:'Micro 5 POP flat fixture — tunable.',url:B+'QTL_POP-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'POP-FLAT (01) Warm Dim',                    cat:'Micro 5', desc:'Micro 5 POP flat fixture — warm dim.',url:B+'QTL_POP-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── MICRO 5 SLITE ──
    {name:'SLITE-ENCAPSULATED (03) RGB',          cat:'Micro 5', desc:'Micro 5 SLITE encapsulated fixture — RGB.',url:B+'QTL_SLITE-ENCAPSULATED__03___RGB.pdf'},
    {name:'SLITE-ENCAPSULATED (03) Static White', cat:'Micro 5', desc:'Micro 5 SLITE encapsulated fixture — static white.',url:B+'QTL_SLITE-ENCAPSULATED__03__STATIC_WHITE.pdf'},
    {name:'SLITE-ENCAPSULATED (03) Tunable',      cat:'Micro 5', desc:'Micro 5 SLITE encapsulated fixture — tunable.',url:B+'QTL_SLITE_ENCAPSULATED__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'SLITE-ENCAPSULATED (03) Warm Dim',     cat:'Micro 5', desc:'Micro 5 SLITE encapsulated fixture — warm dim.',url:B+'QTL_SLITE_ENCAPSULATED__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'SLITE-FLAT (01) RGB',                  cat:'Micro 5', desc:'Micro 5 SLITE flat fixture — RGB.',url:B+'QTL_SLITE-FLAT__01__RGB.pdf'},
    {name:'SLITE-FLAT (01) Static White',         cat:'Micro 5', desc:'Micro 5 SLITE flat fixture — static white.',url:B+'QTL_SLITE-FLAT__01__STATIC_WHITE.pdf'},
    {name:'SLITE-FLAT (01) Tunable',              cat:'Micro 5', desc:'Micro 5 SLITE flat fixture — tunable.',url:B+'QTL_SLITE-FLAT__01___FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'SLITE-FLAT (01) Warm Dim',             cat:'Micro 5', desc:'Micro 5 SLITE flat fixture — warm dim.',url:B+'QTL_SLITE-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── MICRO 5 TILT ──
    {name:'TILT-FLAT (01) RGB',          cat:'Micro 5', desc:'Micro 5 TILT adjustable flat fixture — RGB.',url:B+'QTL_TILT-FLAT__01__RGB.pdf'},
    {name:'TILT-FLAT (01) Static White', cat:'Micro 5', desc:'Micro 5 TILT adjustable flat fixture — static white.',url:B+'QTL_TILT-FLAT__01__STATIC_WHITE.pdf'},
    {name:'TILT-FLAT (01) Tunable',      cat:'Micro 5', desc:'Micro 5 TILT adjustable flat fixture — tunable.',url:B+'QTL_TILT-FLAT__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'TILT-FLAT (01) Warm Dim',     cat:'Micro 5', desc:'Micro 5 TILT adjustable flat fixture — warm dim.',url:B+'QTL_TILT-FLAT__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── OPTI ──
    {name:'OPTI-OPTICS (02) RGB',          cat:'Specialty', desc:'OPTI optics adjustable fixture — RGB.',url:B+'QTL_OPTI-OPTICS__02__RGB.pdf'},
    {name:'OPTI-OPTICS (02) RGBW',         cat:'Specialty', desc:'OPTI optics adjustable fixture — RGBW.',url:B+'QTL_OPTI-OPTICS__02__RGBW.pdf'},
    {name:'OPTI-OPTICS (02) Static Color', cat:'Specialty', desc:'OPTI optics adjustable fixture — static color.',url:B+'QTL_OPTI-OPTICS__02__STATIC_COLOR.pdf'},
    {name:'OPTI-OPTICS (02) Static White', cat:'Specialty', desc:'OPTI optics adjustable fixture — static white/HE.',url:B+'QTL_OPTI-OPTICS__02__STATIC_WHITE.pdf'},
    {name:'OPTI-OPTICS (02) Tunable',      cat:'Specialty', desc:'OPTI optics adjustable fixture — tunable.',url:B+'QTL_OPTI-OPTICS__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'OPTI-OPTICS (02) Warm Dim',     cat:'Specialty', desc:'OPTI optics adjustable fixture — warm dim.',url:B+'QTL_OPTI-OPTICS__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── PERI ──
    {name:'PERI Static White CC', cat:'Specialty', desc:'PERI LED strip — static white constant current.',url:B+'QTL_PERI-SW-CC.pdf'},
    {name:'PERI Static White CV', cat:'Specialty', desc:'PERI LED strip — static white constant voltage.',url:B+'ORD_PERI-SW-CV_QTL.pdf'},
    {name:'PERI Tunable',         cat:'Specialty', desc:'PERI LED strip — tunable white.',url:B+'QTL_PERI-TW.pdf'},
    {name:'PERI Warm Dim',        cat:'Specialty', desc:'PERI LED strip — warm dim.',url:B+'QTL_PERI-WD.pdf'},
    // ── POSH ──
    {name:'POSH Float Static White',        cat:'Specialty', desc:'POSH float architectural linear fixture — static white/HE.',url:B+'QTL_POSH_FLOAT_STATIC_WHITE.pdf'},
    {name:'POSH Wall-to-Wall Static White', cat:'Specialty', desc:'POSH wall-to-wall architectural linear fixture — static white/HE.',url:B+'QTL_POSH_W2W_STATIC_WHITE.pdf'},
    // ── QUOVA ──
    {name:'QUOVA Micro',                                    cat:'Specialty', desc:'QUOVA micro architectural recessed linear.',url:B+'ORD_EXT_QUOVA-MICRO_QTL.pdf'},
    {name:'QUOVA Performance Float Static White HE',        cat:'Specialty', desc:'QUOVA performance float linear — static white high efficacy.',url:B+'QUOVA-PERFORMANCE-FLOAT-SW-HE.pdf'},
    {name:'QUOVA Performance Float Tunable',                cat:'Specialty', desc:'QUOVA performance float linear — tunable.',url:B+'ORD-EXT-QUOVA-FLOAT-TW.pdf'},
    {name:'QUOVA Performance Float Warm Dim',               cat:'Specialty', desc:'QUOVA performance float linear — warm dim.',url:B+'ORD-EXT-QUOVA-FLOAT-WD.pdf'},
    {name:'QUOVA Performance Smooth/Mud-in Static White HE',cat:'Specialty', desc:'QUOVA performance smooth mud-in linear — static white high efficacy.',url:B+'QUOVA-PERFORMANCE-SMOOTH-MUDIN-SW-HE.pdf'},
    {name:'QUOVA Performance Smooth/Mud-in Tunable',        cat:'Specialty', desc:'QUOVA performance smooth mud-in linear — tunable.',url:B+'ORD-EXT-QUOVA-SM_MDIN-TW.pdf'},
    {name:'QUOVA Performance Smooth/Mud-in Warm Dim',       cat:'Specialty', desc:'QUOVA performance smooth mud-in linear — warm dim.',url:B+'ORD-EXT-QUOVA-SM_MDIN-WD.pdf'},
    {name:'QUOVA Performance Standalone Static White HE',   cat:'Specialty', desc:'QUOVA performance standalone linear — static white high efficacy.',url:B+'QUOVA-PERFORMANCE-STANDALONE-SW-HE.pdf'},
    {name:'QUOVA Performance Standalone Tunable',           cat:'Specialty', desc:'QUOVA performance standalone linear — tunable.',url:B+'ORD-EXT-QUOVA-STANDALONE-TW.pdf'},
    {name:'QUOVA Performance Standalone Warm Dim',          cat:'Specialty', desc:'QUOVA performance standalone linear — warm dim.',url:B+'ORD-EXT-QUOVA-STANDALONE-WD.pdf'},
    {name:'QUOVA Standard',                                 cat:'Specialty', desc:'QUOVA standard architectural recessed linear.',url:B+'ORD_EXT_QUOVA_STND_QTL.pdf'},
    // ── VERS Linear ──
    {name:'VERS-ASYMMETRIC (09) RGB',           cat:'VERS Linear', desc:'VERS asymmetric aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-ASYMMETRIC__09__RGB.pdf'},
    {name:'VERS-ASYMMETRIC (09) Static Color',  cat:'VERS Linear', desc:'VERS asymmetric aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-ASYMMETRIC__09__STATIC_COLOR.pdf'},
    {name:'VERS-ASYMMETRIC (09) Static White',  cat:'VERS Linear', desc:'VERS asymmetric aperture linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-ASYMMETRIC__09__STATIC_WHITE.pdf'},
    {name:'VERS-ASYMMETRIC (09) Tunable',       cat:'VERS Linear', desc:'VERS asymmetric aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-ASYMMETRIC__09__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-ASYMMETRIC (09) Warm Dim',      cat:'VERS Linear', desc:'VERS asymmetric aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-ASYMMETRIC__09__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-CLEAR (03) RGB',                cat:'VERS Linear', desc:'VERS clear aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-CLEAR__03__RGB.pdf'},
    {name:'VERS-CLEAR (03) RGBW',               cat:'VERS Linear', desc:'VERS clear aperture linear fixture — RGBW.',url:B+'QTL_LINEAR-VERS-CLEAR__03__RGBW.pdf'},
    {name:'VERS-CLEAR (03) Static Color',       cat:'VERS Linear', desc:'VERS clear aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-CLEAR__03__STATIC_COLOR.pdf'},
    {name:'VERS-CLEAR (03) Static White',       cat:'VERS Linear', desc:'VERS clear aperture linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-CLEAR__03__STATIC_WHITE.pdf'},
    {name:'VERS-CLEAR (03) Tunable',            cat:'VERS Linear', desc:'VERS clear aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-CLEAR__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-CLEAR (03) Warm Dim',           cat:'VERS Linear', desc:'VERS clear aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-CLEAR__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-DROP (10) RGB',                 cat:'VERS Linear', desc:'VERS drop aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-DROP__10__RGB.pdf'},
    {name:'VERS-DROP (10) RGBW',                cat:'VERS Linear', desc:'VERS drop aperture linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LINEAR-VERS-DROP__10__RGBW.pdf'},
    {name:'VERS-DROP (10) Static Color',        cat:'VERS Linear', desc:'VERS drop aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-DROP__10__STATIC_COLOR.pdf'},
    {name:'VERS-DROP (10) Static White',        cat:'VERS Linear', desc:'VERS drop aperture linear fixture — static white.',url:B+'QTL_LINEAR-VERS-DROP__10__STATIC_WHITE.pdf'},
    {name:'VERS-DROP (10) Tunable',             cat:'VERS Linear', desc:'VERS drop aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-DROP__10__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-DROP (10) Warm Dim',            cat:'VERS Linear', desc:'VERS drop aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-DROP__10__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-ENCAPSULATED (06) RGB',         cat:'VERS Linear', desc:'VERS encapsulated linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__RGB.pdf'},
    {name:'VERS-ENCAPSULATED (06) RGBW',        cat:'VERS Linear', desc:'VERS encapsulated linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__RGBW.pdf'},
    {name:'VERS-ENCAPSULATED (06) Static Color',cat:'VERS Linear', desc:'VERS encapsulated linear fixture — static color.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__STATIC_COLOR.pdf'},
    {name:'VERS-ENCAPSULATED (06) Static White',cat:'VERS Linear', desc:'VERS encapsulated linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__STATIC_WHITE.pdf'},
    {name:'VERS-ENCAPSULATED (06) Tunable',     cat:'VERS Linear', desc:'VERS encapsulated linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-ENCAPSULATED (06) Warm Dim',    cat:'VERS Linear', desc:'VERS encapsulated linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-ENCAPSULATED__06__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-FLUSH (02) RGB',                cat:'VERS Linear', desc:'VERS flush aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-FLUSH__02__RGB.pdf'},
    {name:'VERS-FLUSH (02) Static Color',       cat:'VERS Linear', desc:'VERS flush aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-FLUSH__02__STATIC_COLOR.pdf'},
    {name:'VERS-FLUSH (02) Static White',       cat:'VERS Linear', desc:'VERS flush aperture linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-FLUSH__02__STATIC_WHITE.pdf'},
    {name:'VERS-FLUSH (02) Tunable',            cat:'VERS Linear', desc:'VERS flush aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-FLUSH__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-FLUSH (02) Warm Dim',           cat:'VERS Linear', desc:'VERS flush aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-FLUSH__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-GRAZER (04) RGB',               cat:'VERS Linear', desc:'VERS grazer linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-GRAZER__04__RGB.pdf'},
    {name:'VERS-GRAZER (04) RGBW',              cat:'VERS Linear', desc:'VERS grazer linear fixture — RGBW.',url:B+'QTL_LINEAR-VERS-GRAZER__04__RGBW.pdf'},
    {name:'VERS-GRAZER (04) Static Color',      cat:'VERS Linear', desc:'VERS grazer linear fixture — static color.',url:B+'QTL_LINEAR-VERS-GRAZER__04__STATIC_COLOR.pdf'},
    {name:'VERS-GRAZER (04) Static White',      cat:'VERS Linear', desc:'VERS grazer linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-GRAZER__04__STATIC_WHITE.pdf'},
    {name:'VERS-GRAZER (04) Tunable',           cat:'VERS Linear', desc:'VERS grazer linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-GRAZER__04__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-GRAZER (04) Warm Dim',          cat:'VERS Linear', desc:'VERS grazer linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-GRAZER__04__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-INSERT (08) RGB',               cat:'VERS Linear', desc:'VERS insert aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-INSERT__08__RGB.pdf'},
    {name:'VERS-INSERT (08) RGBW',              cat:'VERS Linear', desc:'VERS insert aperture linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LINEAR-VERS-INSERT__08__RGBW.pdf'},
    {name:'VERS-INSERT (08) Static Color',      cat:'VERS Linear', desc:'VERS insert aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-INSERT__08__STATIC_COLOR.pdf'},
    {name:'VERS-INSERT (08) Static White',      cat:'VERS Linear', desc:'VERS insert aperture linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-INSERT__08__STATIC_WHITE.pdf'},
    {name:'VERS-INSERT (08) Tunable',           cat:'VERS Linear', desc:'VERS insert aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-INSERT__08__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-INSERT (08) Warm Dim',          cat:'VERS Linear', desc:'VERS insert aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-INSERT__08__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-LOUVER (07) RGB',               cat:'VERS Linear', desc:'VERS louver linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-LOUVER__07__RGB.pdf'},
    {name:'VERS-LOUVER (07) RGBW',              cat:'VERS Linear', desc:'VERS louver linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LINEAR-VERS-LOUVER__07__RGBW.pdf'},
    {name:'VERS-LOUVER (07) Static Color',      cat:'VERS Linear', desc:'VERS louver linear fixture — static color.',url:B+'QTL_LINEAR-VERS-LOUVER__07__STATIC_COLOR.pdf'},
    {name:'VERS-LOUVER (07) Static White',      cat:'VERS Linear', desc:'VERS louver linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-LOUVER__07__STATIC_WHITE.pdf'},
    {name:'VERS-LOUVER (07) Tunable',           cat:'VERS Linear', desc:'VERS louver linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-LOUVER__07__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-LOUVER (07) Warm Dim',          cat:'VERS Linear', desc:'VERS louver linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-LOUVER__07__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-NANO-LOUVER (11) RGB',          cat:'VERS Linear', desc:'VERS nano-louver linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__RGB.pdf'},
    {name:'VERS-NANO-LOUVER (11) RGBW',         cat:'VERS Linear', desc:'VERS nano-louver linear fixture — RGBW/RGBW-HE.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__RGBW.pdf'},
    {name:'VERS-NANO-LOUVER (11) Static Color', cat:'VERS Linear', desc:'VERS nano-louver linear fixture — static color.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__STATIC_COLOR.pdf'},
    {name:'VERS-NANO-LOUVER (11) Static White', cat:'VERS Linear', desc:'VERS nano-louver linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__STATIC_WHITE.pdf'},
    {name:'VERS-NANO-LOUVER (11) Tunable',      cat:'VERS Linear', desc:'VERS nano-louver linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-NANO-LOUVER (11) Warm Dim',     cat:'VERS Linear', desc:'VERS nano-louver linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-NANO-LOUVER__11__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-OPTICS (05) RGB',               cat:'VERS Linear', desc:'VERS optics linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-OPTICS__05__RGB.pdf'},
    {name:'VERS-OPTICS (05) Static Color',      cat:'VERS Linear', desc:'VERS optics linear fixture — static color.',url:B+'QTL_LINEAR-VERS-OPTICS__05__STATIC_COLOR.pdf'},
    {name:'VERS-OPTICS (05) Static White',      cat:'VERS Linear', desc:'VERS optics linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-OPTICS__05__STATIC_WHITE.pdf'},
    {name:'VERS-OPTICS (05) Tunable',           cat:'VERS Linear', desc:'VERS optics linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-OPTICS__05__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-OPTICS (05) Warm Dim',          cat:'VERS Linear', desc:'VERS optics linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-OPTICS__05__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-PROUD (01) RGB',                cat:'VERS Linear', desc:'VERS proud aperture linear fixture — RGB.',url:B+'QTL_LINEAR-VERS-PROUD__01__RGB.pdf'},
    {name:'VERS-PROUD (01) RGBW',               cat:'VERS Linear', desc:'VERS proud aperture linear fixture — RGBW.',url:B+'QTL_LINEAR-VERS-PROUD__01__RGBW.pdf'},
    {name:'VERS-PROUD (01) Static Color',       cat:'VERS Linear', desc:'VERS proud aperture linear fixture — static color.',url:B+'QTL_LINEAR-VERS-PROUD__01__STATIC_COLOR.pdf'},
    {name:'VERS-PROUD (01) Static White',       cat:'VERS Linear', desc:'VERS proud aperture linear fixture — static white/HE.',url:B+'QTL_LINEAR-VERS-PROUD__01__STATIC_WHITE.pdf'},
    {name:'VERS-PROUD (01) Tunable',            cat:'VERS Linear', desc:'VERS proud aperture linear fixture — tunable.',url:B+'QTL_LINEAR-VERS-PROUD__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-PROUD (01) Warm Dim',           cat:'VERS Linear', desc:'VERS proud aperture linear fixture — warm dim.',url:B+'QTL_LINEAR-VERS-PROUD__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── VERS Suspended ──
    {name:'VERS-ASYMMETRIC-SK (09) RGB',           cat:'VERS Suspended', desc:'VERS suspended asymmetric linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-ASYMMETRIC-SK__09__RGB.pdf'},
    {name:'VERS-ASYMMETRIC-SK (09) Static Color',  cat:'VERS Suspended', desc:'VERS suspended asymmetric linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-ASYMMETRIC-SK__09__STATIC_COLOR.pdf'},
    {name:'VERS-ASYMMETRIC-SK (09) Static White',  cat:'VERS Suspended', desc:'VERS suspended asymmetric linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-ASYMMETRIC-SK__09__STATIC_WHITE.pdf'},
    {name:'VERS-ASYMMETRIC-SK (09) Tunable',       cat:'VERS Suspended', desc:'VERS suspended asymmetric linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-ASYMMETRIC-SK__09__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-ASYMMETRIC-SK (09) Warm Dim',      cat:'VERS Suspended', desc:'VERS suspended asymmetric linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-ASYMMETRIC-SK__09__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-CLEAR-SK (03) RGB',                cat:'VERS Suspended', desc:'VERS suspended clear aperture linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-CLEAR-SK__03__RGB.pdf'},
    {name:'VERS-CLEAR-SK (03) Static Color',       cat:'VERS Suspended', desc:'VERS suspended clear aperture linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-CLEAR-SK__03__STATIC_COLOR.pdf'},
    {name:'VERS-CLEAR-SK (03) Static White',       cat:'VERS Suspended', desc:'VERS suspended clear aperture linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-CLEAR-SK__03__STATIC_WHITE.pdf'},
    {name:'VERS-CLEAR-SK (03) Tunable',            cat:'VERS Suspended', desc:'VERS suspended clear aperture linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-CLEAR-SK__03__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-CLEAR-SK (03) Warm Dim',           cat:'VERS Suspended', desc:'VERS suspended clear aperture linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-CLEAR-SK__03__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-DROP-SK (10) RGB',                 cat:'VERS Suspended', desc:'VERS suspended drop aperture linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-DROP-SK__10__RGB.pdf'},
    {name:'VERS-DROP-SK (10) Static Color',        cat:'VERS Suspended', desc:'VERS suspended drop aperture linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-DROP-SK__10__STATIC_COLOR.pdf'},
    {name:'VERS-DROP-SK (10) Static White',        cat:'VERS Suspended', desc:'VERS suspended drop aperture linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-DROP-SK__10__STATIC_WHITE.pdf'},
    {name:'VERS-DROP-SK (10) Tunable',             cat:'VERS Suspended', desc:'VERS suspended drop aperture linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-DROP-SK__10__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-DROP-SK (10) Warm Dim',            cat:'VERS Suspended', desc:'VERS suspended drop aperture linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-DROP-SK__10__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-FLUSH-SK (02) RGB',                cat:'VERS Suspended', desc:'VERS suspended flush linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-FLUSH-SK__02__RGB.pdf'},
    {name:'VERS-FLUSH-SK (02) Static Color',       cat:'VERS Suspended', desc:'VERS suspended flush linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-FLUSH-SK__02__STATIC_COLOR.pdf'},
    {name:'VERS-FLUSH-SK (02) Static White',       cat:'VERS Suspended', desc:'VERS suspended flush linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-FLUSH-SK__02__STATIC_WHITE.pdf'},
    {name:'VERS-FLUSH-SK (02) Tunable',            cat:'VERS Suspended', desc:'VERS suspended flush linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-FLUSH-SK__02__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-FLUSH-SK (02) Warm Dim',           cat:'VERS Suspended', desc:'VERS suspended flush linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-FLUSH-SK__02__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-GRAZER-SK (04) RGB',               cat:'VERS Suspended', desc:'VERS suspended grazer linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-GRAZER-SK__04__RGB.pdf'},
    {name:'VERS-GRAZER-SK (04) Static Color',      cat:'VERS Suspended', desc:'VERS suspended grazer linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-GRAZER-SK__04__STATIC_COLOR.pdf'},
    {name:'VERS-GRAZER-SK (04) Static White',      cat:'VERS Suspended', desc:'VERS suspended grazer linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-GRAZER-SK__04__STATIC_WHITE.pdf'},
    {name:'VERS-GRAZER-SK (04) Tunable',           cat:'VERS Suspended', desc:'VERS suspended grazer linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-GRAZER-SK__04__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-GRAZER-SK (04) Warm Dim',          cat:'VERS Suspended', desc:'VERS suspended grazer linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-GRAZER-SK__04__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-INSERT-SK (08) RGB',               cat:'VERS Suspended', desc:'VERS suspended insert aperture linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-INSERT-SK__08__RGB.pdf'},
    {name:'VERS-INSERT-SK (08) Static Color',      cat:'VERS Suspended', desc:'VERS suspended insert aperture linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-INSERT-SK__08__STATIC_COLOR.pdf'},
    {name:'VERS-INSERT-SK (08) Static White',      cat:'VERS Suspended', desc:'VERS suspended insert aperture linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-INSERT-SK__08__STATIC_WHITE.pdf'},
    {name:'VERS-INSERT-SK (08) Tunable',           cat:'VERS Suspended', desc:'VERS suspended insert aperture linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-INSERT-SK__08__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-INSERT-SK (08) Warm Dim',          cat:'VERS Suspended', desc:'VERS suspended insert aperture linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-INSERT-SK__08__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-LOUVER-SK (07) RGB',               cat:'VERS Suspended', desc:'VERS suspended louver linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-LOUVER-SK__07__RGB.pdf'},
    {name:'VERS-LOUVER-SK (07) Static Color',      cat:'VERS Suspended', desc:'VERS suspended louver linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-LOUVER-SK__07__STATIC_COLOR.pdf'},
    {name:'VERS-LOUVER-SK (07) Static White',      cat:'VERS Suspended', desc:'VERS suspended louver linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-LOUVER-SK__07__STATIC_WHITE.pdf'},
    {name:'VERS-LOUVER-SK (07) Tunable',           cat:'VERS Suspended', desc:'VERS suspended louver linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-LOUVER-SK__07__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-LOUVER-SK (07) Warm Dim',          cat:'VERS Suspended', desc:'VERS suspended louver linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-LOUVER-SK__07__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-NANO-LOUVER-SK (11) RGB',          cat:'VERS Suspended', desc:'VERS suspended nano-louver linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-NANO-LOUVER-SK__11__RGB.pdf'},
    {name:'VERS-NANO-LOUVER-SK (11) Static Color', cat:'VERS Suspended', desc:'VERS suspended nano-louver linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-NANO-LOUVER-SK__11__STATIC_COLOR.pdf'},
    {name:'VERS-NANO-LOUVER-SK (11) Static White', cat:'VERS Suspended', desc:'VERS suspended nano-louver linear — static white/HE.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-NANO-LOUVER-SK__11__STATIC_WHITE.pdf'},
    {name:'VERS-NANO-LOUVER-SK (11) Tunable',      cat:'VERS Suspended', desc:'VERS suspended nano-louver linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-NANO-LOUVER-SK__11__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-NANO-LOUVER-SK (11) Warm Dim',     cat:'VERS Suspended', desc:'VERS suspended nano-louver linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-NANO-LOUVER-SK__11__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-OPTICS-SK (05) RGB',               cat:'VERS Suspended', desc:'VERS suspended optics linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-OPTICS-SK__05__RGB.pdf'},
    {name:'VERS-OPTICS-SK (05) Static Color',      cat:'VERS Suspended', desc:'VERS suspended optics linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-OPTICS-SK__05__STATIC_COLOR.pdf'},
    {name:'VERS-OPTICS-SK (05) Static White',      cat:'VERS Suspended', desc:'VERS suspended optics linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-OPTICS-SK__05__STATIC_WHITE.pdf'},
    {name:'VERS-OPTICS-SK (05) Tunable',           cat:'VERS Suspended', desc:'VERS suspended optics linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-OPTICS-SK__05__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-OPTICS-SK (05) Warm Dim',          cat:'VERS Suspended', desc:'VERS suspended optics linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-OPTICS-SK__05__FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'VERS-PROUD-SK (01) RGB',                cat:'VERS Suspended', desc:'VERS suspended proud aperture linear — RGB.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-PROUD-SK__01__RGB.pdf'},
    {name:'VERS-PROUD-SK (01) Static Color',       cat:'VERS Suspended', desc:'VERS suspended proud aperture linear — static color.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-PROUD-SK__01__STATIC_COLOR.pdf'},
    {name:'VERS-PROUD-SK (01) Static White',       cat:'VERS Suspended', desc:'VERS suspended proud aperture linear — static white.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-PROUD-SK__01__STATIC_WHITE.pdf'},
    {name:'VERS-PROUD-SK (01) Tunable',            cat:'VERS Suspended', desc:'VERS suspended proud aperture linear — tunable.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-PROUD-SK__01__FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'VERS-PROUD-SK (01) Warm Dim',           cat:'VERS Suspended', desc:'VERS suspended proud aperture linear — warm dim.',url:B+'QTL_LINEAR-VERS-SUSPENDED_VERS-PROUD-SK__01__FOR_WARM_DIM_APPLICATIONS.pdf'},
    // ── FLEX LIGHT ──
    {name:'Flex Light DOME-SC',      cat:'Flex Light', desc:'Flexible LED DOME fixture — static color.',url:F+'ORD-FLEX-DomeSC.pdf'},
    {name:'Flex Light DOME-SW',      cat:'Flex Light', desc:'Flexible LED DOME fixture — static white.',url:F+'ORD-FLEX-DomeWhite.pdf'},
    {name:'Flex Light MEZA-DW',      cat:'Flex Light', desc:'Flexible LED MEZA fixture — dual white.',url:B+'ORD-FLEX-MezaDW.pdf'},
    {name:'Flex Light MEZA-RGB',     cat:'Flex Light', desc:'Flexible LED MEZA fixture — RGB.',url:B+'ORD-FLEX-MezaRGB.pdf'},
    {name:'Flex Light MEZA-RGBW',    cat:'Flex Light', desc:'Flexible LED MEZA fixture — RGBW.',url:F+'ORD-FLEX-MezaRGBW.pdf'},
    {name:'Flex Light MEZA-SC',      cat:'Flex Light', desc:'Flexible LED MEZA fixture — static color.',url:B+'ORD-FLEX-MezaSC.pdf'},
    {name:'Flex Light MEZA-SW',      cat:'Flex Light', desc:'Flexible LED MEZA fixture — static white.',url:B+'ORD-FLEX-MezaWhite.pdf'},
    {name:'Flex Light MINI-SC',      cat:'Flex Light', desc:'Flexible LED MINI fixture — static color.',url:F+'ORD-FLEX-MiniSC.pdf'},
    {name:'Flex Light MINI-SW',      cat:'Flex Light', desc:'Flexible LED MINI fixture — static white.',url:F+'ORD-FLEX-MiniWhite.pdf'},
    {name:'Flex Light OUTERBEND-SW', cat:'Flex Light', desc:'Flexible LED OUTERBEND fixture — static white.',url:F+'ORD-FLEX-OBD.pdf'},
    // ── Q-CAP ──
    {name:'Q-CAP ANYBEND RGB',             cat:'Q-CAP Flexible', desc:'Q-CAP ANYBEND flexible fixture — RGB.',url:B+'QTL_ANYBEND_RGB.pdf'},
    {name:'Q-CAP ANYBEND Static White',    cat:'Q-CAP Flexible', desc:'Q-CAP ANYBEND flexible fixture — static white.',url:B+'QTL_ANYBEND_STATIC_WHITE.pdf'},
    {name:'Q-CAP ANYBEND Tunable',         cat:'Q-CAP Flexible', desc:'Q-CAP ANYBEND flexible fixture — tunable.',url:B+'QTL_ANYBEND_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP ANYBEND Warm Dim',        cat:'Q-CAP Flexible', desc:'Q-CAP ANYBEND flexible fixture — warm dim.',url:B+'QTL_ANYBEND_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP BOXA RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — RGB.',url:B+'QTL_BOXA_RGB.pdf'},
    {name:'Q-CAP BOXA RGBW',               cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — RGBW.',url:B+'QTL_BOXA_RGBW.pdf'},
    {name:'Q-CAP BOXA RGBW High Efficacy', cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — RGBW high efficacy.',url:B+'QTL_BOXA_RGBW_HIGH_EFFICACY.pdf'},
    {name:'Q-CAP BOXA Static Color',       cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — static color.',url:B+'QTL_BOXA_STATIC_COLOR.pdf'},
    {name:'Q-CAP BOXA Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — static white/HE.',url:B+'QTL_BOXA_STATIC_WHITE.pdf'},
    {name:'Q-CAP BOXA Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — tunable.',url:B+'QTL_BOXA_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP BOXA Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP BOXA flexible fixture — warm dim.',url:B+'QTL_BOXA_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP KURV RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — RGB.',url:B+'QTL_KURV_RGB.pdf'},
    {name:'Q-CAP KURV RGBW',               cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — RGBW.',url:B+'QTL_KURV_RGBW.pdf'},
    {name:'Q-CAP KURV RGBW High Efficacy', cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — RGBW high efficacy.',url:B+'QTL_KURV_RGBW_HIGH_EFFICACY.pdf'},
    {name:'Q-CAP KURV Static Color',       cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — static color.',url:B+'QTL_KURV_STATIC_COLOR.pdf'},
    {name:'Q-CAP KURV Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — static white/HE.',url:B+'QTL_KURV_STATIC_WHITE.pdf'},
    {name:'Q-CAP KURV Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — tunable.',url:B+'QTL_KURV_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP KURV Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP KURV side-bending flexible fixture — warm dim.',url:B+'QTL_KURV_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP KURV-BK RGB',             cat:'Q-CAP Flexible', desc:'Q-CAP KURV-BK side-bending flexible fixture (black) — RGB.',url:B+'QTL_KURV-BK_RGB.pdf'},
    {name:'Q-CAP LUME Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP LUME up/down-bending flexible fixture — static white/HE.',url:B+'QTL_LUME-01_STATIC_WHITE.pdf'},
    {name:'Q-CAP LUME RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP LUME up/down-bending flexible fixture — RGB.',url:B+'QTL_LUME-01_RGB.pdf'},
    {name:'Q-CAP LUME Static Color',       cat:'Q-CAP Flexible', desc:'Q-CAP LUME up/down-bending flexible fixture — static color.',url:B+'QTL_LUME-01_STATIC_COLOR.pdf'},
    {name:'Q-CAP LUME Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP LUME up/down-bending flexible fixture — tunable.',url:B+'QTL_LUME-01_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP LUME Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP LUME up/down-bending flexible fixture — warm dim.',url:B+'QTL_LUME-01_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP NEXUS Static White',      cat:'Q-CAP Flexible', desc:'Q-CAP NEXUS helical & up/down-bending flexible fixture — static white.',url:B+'QTL_NEXUS_STATIC_WHITE.pdf'},
    {name:'Q-CAP WALA Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP WALA side-bending flexible fixture — static white.',url:B+'QTL_WALA_STATIC_WHITE.pdf'},
    {name:'Q-CAP WALA RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP WALA side-bending flexible fixture — RGB.',url:B+'QTL_WALA_RGB.pdf'},
    {name:'Q-CAP WALA Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP WALA side-bending flexible fixture — tunable.',url:B+'QTL_WALA_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP WALA Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP WALA side-bending flexible fixture — warm dim.',url:B+'QTL_WALA_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP WAVE Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP WAVE up/down-bending flexible fixture — static white.',url:B+'QTL_WAVE_STATIC_WHITE.pdf'},
    {name:'Q-CAP WAVE RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP WAVE up/down-bending flexible fixture — RGB.',url:B+'QTL_WAVE_RGB.pdf'},
    {name:'Q-CAP WAVE Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP WAVE up/down-bending flexible fixture — tunable.',url:B+'QTL_WAVE_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP WAVE Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP WAVE up/down-bending flexible fixture — warm dim.',url:B+'QTL_WAVE_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP WURM Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — static white.',url:B+'QTL_WURM_STATIC_WHITE.pdf'},
    {name:'Q-CAP WURM RGB',                cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — RGB.',url:B+'QTL_WURM_RGB.pdf'},
    {name:'Q-CAP WURM RGBW',               cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — RGBW.',url:B+'QTL_WURM_RGBW.pdf'},
    {name:'Q-CAP WURM RGBW High Efficacy', cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — RGBW high efficacy.',url:B+'QTL_WURM_RGBW-HE.pdf'},
    {name:'Q-CAP WURM Tunable',            cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — tunable.',url:B+'QTL_WURM_FOR_TUNABLE_APPLICATIONS.pdf'},
    {name:'Q-CAP WURM Warm Dim',           cat:'Q-CAP Flexible', desc:'Q-CAP WURM up/down & helical bending flexible fixture — warm dim.',url:B+'QTL_WURM_FOR_WARM_DIM_APPLICATIONS.pdf'},
    {name:'Q-CAP ZALA Static White',       cat:'Q-CAP Flexible', desc:'Q-CAP ZALA side-bending flexible fixture — static white.',url:B+'QTL_ZALA_STATIC_WHITE.pdf'},
    {name:'Q-CAP ZALA Static Color',       cat:'Q-CAP Flexible', desc:'Q-CAP ZALA side-bending flexible fixture — static color.',url:B+'QTL_ZALA_STATIC_COLOR.pdf'},
    // LED Channel
    {name:'MDIN',                          cat:'LED Channel',     desc:'MDIN flush installation LED aluminum extrusion profile.',url:B+'QTL_MDIN.pdf'},
    // Power Supply — DC Indoor
    {name:'iQ-PH (iQ-PH-QD1)',            cat:'Power Supply — DC Indoor', desc:'iQ-PH-QD1 DC LED power supply — phase dimming.',url:B+'QTL_iQ-PH-QD1.pdf'},
    {name:'Q6M-DC+CAP',                   cat:'Power Supply — DC Indoor', desc:'Q6M DC+CAP indoor LED power supply.',url:B+'QTL_Q6M-DC_CAP.pdf'},
    {name:'QTM-DC+CAP',                   cat:'Power Supply — DC Indoor', desc:'QTM DC+CAP indoor LED power supply.',url:B+'QTL_QTM-DC_CAP.pdf'},
    {name:'QTM-eLED+TW',                  cat:'Power Supply — DC Indoor', desc:'QTM eLED+TW indoor LED power supply — tunable white.',url:B+'QTL_QTM-eLED_TW.pdf'},
    {name:'QTM-eLED+WD',                  cat:'Power Supply — DC Indoor', desc:'QTM eLED+WD indoor LED power supply — warm dim.',url:B+'QTL_QTM-eLED_WD.pdf'},
    {name:'QTM-eLED+DMX',                 cat:'Power Supply — DC Indoor', desc:'QTM eLED+DMX indoor LED power supply — DMX dimming.',url:B+'QTL_QTM-eLED_DMX.pdf'},
    {name:'QTM-eLED+IA',                  cat:'Power Supply — DC Indoor', desc:'QTM eLED+IA indoor LED power supply — Lutron Ivalo Athena.',url:B+'QTL_QTM-eLED_IA.pdf'},
    {name:'QTM-eLED(E)',                   cat:'Power Supply — DC Indoor', desc:'QTM eLED(E) indoor LED power supply — extended control.',url:B+'QTL_QTM-eLEDE.pdf'},
    {name:'QTM-eLED+DALI-DT6',            cat:'Power Supply — DC Indoor', desc:'QTM eLED+DALI-DT6 indoor LED power supply — DALI-2 DT-6.',url:B+'QTL_QTM-eLED-DALI-DT6.pdf'},
    {name:'QTM-eLED+DALI-DT8',            cat:'Power Supply — DC Indoor', desc:'QTM eLED+DALI-DT8 indoor LED power supply — DALI-2 DT-8.',url:B+'QTL_QTM-eLED-DALI-DT8.pdf'},
    {name:'QTM-eLED+0-10V',               cat:'Power Supply — DC Indoor', desc:'QTM eLED+0-10V indoor LED power supply — 0-10V dimming.',url:B+'QTL_QTM-eLED_0-10V.pdf'},
    {name:'QTM-eLED-ND',                  cat:'Power Supply — DC Indoor', desc:'QTM eLED-ND indoor LED power supply — non-dimming.',url:B+'QTL_QTM-eLED-ND.pdf'},
    {name:'QTM-eLED+WD-AWN',              cat:'Power Supply — DC Indoor', desc:'QTM eLED+WD-AWN indoor LED power supply — warm dim with Lutron Athena wireless.',url:B+'QTL_QTM-eLED-WD-AWN.pdf'},
    {name:'QTM-eLED+DALI-DT6-AWN',       cat:'Power Supply — DC Indoor', desc:'QTM eLED+DALI-DT6-AWN indoor LED power supply — DALI-2 DT-6 with Athena wireless.',url:B+'QTL_QTM-eLED-DALI-DT6-AWN.pdf'},
    {name:'QTM-eLED+0-10V-AWN',           cat:'Power Supply — DC Indoor', desc:'QTM eLED+0-10V-AWN indoor LED power supply — 0-10V with Athena wireless.',url:B+'QTL_QTM-eLED-0-10V-AWN.pdf'},
    {name:'QTM-eLED+DALI-DT8-AWN',       cat:'Power Supply — DC Indoor', desc:'QTM eLED+DALI-DT8-AWN indoor LED power supply — DALI-2 DT-8 with Athena wireless.',url:B+'QTL_QTM-eLED-DALI-DT8-AWN.pdf'},
    {name:'QZ-ND',                         cat:'Power Supply — DC Indoor', desc:'QZ-ND Class 2 constant voltage DC LED driver — non-dimming.',url:B+'QTL_QZ-ND.pdf'},
    // Power Supply — DC Outdoor
    {name:'QOM-DC+CAP',                   cat:'Power Supply — DC Outdoor', desc:'QOM DC+CAP outdoor LED power supply.',url:B+'QTL_QOM-DC_CAP.pdf'},
    {name:'QOM-eLED+TW',                  cat:'Power Supply — DC Outdoor', desc:'QOM eLED+TW outdoor LED power supply — tunable white.',url:B+'QTL_QOM-eLED_TW.pdf'},
    {name:'QOM-eLED+WD',                  cat:'Power Supply — DC Outdoor', desc:'QOM eLED+WD outdoor LED power supply — warm dim.',url:B+'QTL_QOM-eLED_WD.pdf'},
    {name:'QOM-eLED+DMX',                 cat:'Power Supply — DC Outdoor', desc:'QOM eLED+DMX outdoor LED power supply — DMX dimming.',url:B+'QTL_QOM-eLED_DMX.pdf'},
    {name:'QOM-eLED+IA',                  cat:'Power Supply — DC Outdoor', desc:'QOM eLED+IA outdoor LED power supply — Lutron Ivalo Athena.',url:B+'QTL_QOM-eLED_IA.pdf'},
    {name:'QOM-PH',                        cat:'Power Supply — DC Outdoor', desc:'QOM-PH outdoor LED power supply — phase dimming.',url:B+'QTL_QOM-PH.pdf'},
    {name:'QOM-eLED+DALI-DT6',            cat:'Power Supply — DC Outdoor', desc:'QOM eLED+DALI-DT6 outdoor LED power supply — DALI-2 DT-6.',url:B+'QTL_QOM-eLED-DALI-DT6.pdf'},
    {name:'QOM-eLED+DALI-DT8',            cat:'Power Supply — DC Outdoor', desc:'QOM eLED+DALI-DT8 outdoor LED power supply — DALI-2 DT-8.',url:B+'QTL_QOM-eLED-DALI-DT8.pdf'},
    {name:'QOM-eLED+0-10V',               cat:'Power Supply — DC Outdoor', desc:'QOM eLED+0-10V outdoor LED power supply — 0-10V dimming.',url:B+'QTL_QOM-eLED_0-10V.pdf'},
    {name:'QOM-eLED-ND',                  cat:'Power Supply — DC Outdoor', desc:'QOM eLED-ND outdoor LED power supply — non-dimming.',url:B+'QTL_QOM-eLED-ND.pdf'},
    {name:'Q-SET-mLED',                   cat:'Power Supply — DC Outdoor', desc:'Q-SET-mLED direct burial LED power supply — magnetic.',url:B+'QTL_Q-SET-mLED.pdf'},
    {name:'Q-SET-eLED+0-10V',             cat:'Power Supply — DC Outdoor', desc:'Q-SET-eLED+0-10V direct burial LED power supply — 0-10V dimming.',url:B+'QTL_QSET-eLED-0-10V.pdf'},
    {name:'Q-SET-eLED+ND',                cat:'Power Supply — DC Outdoor', desc:'Q-SET-eLED+ND direct burial LED power supply — non-dimming.',url:B+'QTL_QSET-eLED-ND.pdf'},
    {name:'Q-VAULT-5',                    cat:'Power Supply — DC Outdoor', desc:'Q-VAULT-5 outdoor DC LED power supply vault.',url:B+'QTL_QVAULT5.pdf'},
    // Power Supply — DC Pool/Spa
    {name:'QOM-PH-PS',                    cat:'Power Supply — DC Pool/Spa', desc:'QOM-PH-PS pool & spa LED power supply — phase dimming.',url:B+'QTL_QOM-PH-PS.pdf'},
    {name:'QOM-eLED+TW-PS',              cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+TW-PS pool & spa LED power supply — tunable white.',url:B+'QTL_QOM-eLED_TW-PS.pdf'},
    {name:'QOM-eLED+WD-PS',              cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+WD-PS pool & spa LED power supply — warm dim.',url:B+'QTL_QOM-eLED_WD-PS.pdf'},
    {name:'QOM-eLED+DMX-PS',             cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+DMX-PS pool & spa LED power supply — DMX.',url:B+'QTL_QOM-eLED_DMX-PS.pdf'},
    {name:'QOM-eLED+0-10V-PS',           cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+0-10V-PS pool & spa LED power supply — 0-10V dimming.',url:B+'QTL_QOM-eLED_0-10V-PS.pdf'},
    {name:'QOM-eLED-ND-PS',              cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED-ND-PS pool & spa LED power supply — non-dimming.',url:B+'QTL_QOM-eLED-ND-PS.pdf'},
    {name:'QOM-eLED+DALI-DT6-PS',        cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+DALI-DT6-PS pool & spa LED power supply — DALI-2 DT-6.',url:B+'QTL_QOM-eLED_DALI-DT6-PS.pdf'},
    {name:'QOM-eLED+DALI-DT8-PS',        cat:'Power Supply — DC Pool/Spa', desc:'QOM eLED+DALI-DT8-PS pool & spa LED power supply — DALI-2 DT-8.',url:B+'QTL_QOM-eLED_DALI-DT8-PS.pdf'},
    // Power Supply — DC Landscape
    {name:'Q-HEX-MINI (DC)',              cat:'Power Supply — DC Landscape', desc:'Q-HEX-MINI DC landscape LED power supply — 10W–60W.',url:B+'QTL_Q-HEX-mini-DC.pdf'},
    {name:'Q-TRIX-R50',                   cat:'Power Supply — DC Landscape', desc:'Q-TRIX-R50 landscape DC LED power supply.',url:B+'QTL_QTRIX-R50.pdf'},
    {name:'Q-SET+QZ-ND',                  cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ-ND compact landscape LED power supply — non-dimming.',url:B+'QTL_Q-SET_QZ-ND.pdf'},
    {name:'Q-SET+QZ-PH/0-10V',           cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ landscape LED power supply — phase & 0-10V dimming.',url:B+'QTL_Q-SET_QZ-PH-0-10V.pdf'},
    {name:'Q-SET+QZ-DALI-DT6',           cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ landscape LED power supply — DALI-2 DT-6.',url:B+'QTL_Q-SET_QZ-DALI-DT6.pdf'},
    {name:'Q-SET+QZ-DALI-DT8',           cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ landscape LED power supply — DALI-2 DT-8.',url:B+'QTL_Q-SET_QZ-DALI-DT8.pdf'},
    {name:'Q-SET+QZ-DMX',                 cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ landscape LED power supply — DMX.',url:B+'QTL_Q-SET_QZ-DMX.pdf'},
    {name:'Q-SET+QZ-DW',                  cat:'Power Supply — DC Landscape', desc:'Q-SET+QZ landscape LED power supply — dynamic white.',url:B+'QTL_Q-SET_QZ-DW.pdf'},
    // Power Supply — AC Indoor
    {name:'Q6S',                           cat:'Power Supply — AC Indoor', desc:'Q6S AC LED power supply — small enclosed indoor.',url:B+'QTL_Q6S.pdf'},
    {name:'Q6M',                           cat:'Power Supply — AC Indoor', desc:'Q6M AC LED power supply — medium enclosed indoor.',url:B+'QTL_Q6M.pdf'},
    {name:'QTMS',                          cat:'Power Supply — AC Indoor', desc:'QTMS AC LED power supply — single-circuit enclosed.',url:B+'QTL_QTMS.pdf'},
    {name:'QTMD',                          cat:'Power Supply — AC Indoor', desc:'QTMD AC LED power supply — dual-circuit enclosed.',url:B+'QTL_QTMD.pdf'},
    {name:'QTLQ',                          cat:'Power Supply — AC Indoor', desc:'QTLQ AC LED power supply — quad-circuit enclosed.',url:B+'QTL_QTLQ.pdf'},
    {name:'QTLT',                          cat:'Power Supply — AC Indoor', desc:'QTLT AC LED power supply — triple-circuit enclosed.',url:B+'QTL_QTLT.pdf'},
    {name:'QTLS',                          cat:'Power Supply — AC Indoor', desc:'QTLS AC LED power supply — single-circuit slim.',url:B+'QTL_QTLS.pdf'},
    {name:'QTLD',                          cat:'Power Supply — AC Indoor', desc:'QTLD AC LED power supply — dual-circuit slim.',url:B+'QTL_QTLD.pdf'},
    {name:'QJB',                           cat:'Power Supply — AC Indoor', desc:'QJB junction box LED power supply — indoor.',url:B+'QTL_QJB.pdf'},
    {name:'QJBL',                          cat:'Power Supply — AC Indoor', desc:'QJBL large junction box LED power supply — indoor.',url:B+'QTL_QJBL.pdf'},
    // Power Supply — AC Outdoor
    {name:'QOMS',                          cat:'Power Supply — AC Outdoor', desc:'QOMS AC outdoor LED power supply — single circuit.',url:B+'QTL_QOMS.pdf'},
    {name:'QOMD',                          cat:'Power Supply — AC Outdoor', desc:'QOMD AC outdoor LED power supply — dual circuit.',url:B+'QTL_QOMD.pdf'},
    {name:'Q-SET-1',                       cat:'Power Supply — AC Outdoor', desc:'Q-SET-1 AC outdoor LED power supply — single channel.',url:B+'QTL_Q-SET-1.pdf'},
    {name:'Q-SET-2',                       cat:'Power Supply — AC Outdoor', desc:'Q-SET-2 AC outdoor LED power supply — dual channel.',url:B+'QTL_Q-SET-2.pdf'},
    {name:'Q-SET-3',                       cat:'Power Supply — AC Outdoor', desc:'Q-SET-3 AC outdoor LED power supply — triple channel.',url:B+'QTL_Q-SET-3.pdf'},
    // Power Supply — AC Landscape
    {name:'Q-HEX',                         cat:'Power Supply — AC Landscape', desc:'Q-HEX AC landscape LED power supply — 60W–300W.',url:B+'QTL_QHEX.pdf'},
    {name:'Q-HEX-MINI (AC)',              cat:'Power Supply — AC Landscape', desc:'Q-HEX-MINI AC landscape LED power supply — compact.',url:B+'QTL_Q-HEX-mini.pdf'}
  ];
})();
